import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";

import Contact from "../../components/home/contact";
import List from "./list";
import Map from "./map";

const Contato: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Kalloo English School</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <List />
                <Map />
                <Contact />
            </main>
        </div>
    );
};

export default Contato;
