import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";

import Faq from "./faq";
import Header from "./header";

const Sobre: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Kalloo English School</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Main>
                <Header />
                <Faq />
            </Main>
        </div>
    );
};

export default Sobre;

const Main = styled.main``;
