import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";

import Faq from "./faq";
import styles from "../../styles/Home.module.css";

const Sobre: NextPage = () => {
    return (
        <div className={styles.container} data-test="comp-sobre">
            <Head>
                <title>Kalloo English School</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Main className={styles.main}>
                <Faq />
            </Main>
        </div>
    );
};

export default Sobre;

const Main = styled.main``;
