import type { NextPage } from "next";
import Head from "next/head";

import Levels from "./levels";
import Header from "./header";

const Cursos: NextPage = () => {
    return (
        <div data-test="comp-cursos">
            <Head>
                <title>Kalloo English School</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Header />
                <Levels />
            </main>
        </div>
    );
};

export default Cursos;
