import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import Hero from "../components/home/hero";
import Contact from "../components/home/contact";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    return (
        <div className={styles.container} data-test="comp-home">
            <Head>
                <title>Kalloo English School</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Hero />
                <Contact />
            </main>
        </div>
    );
};

export default Home;
